### ISSUE TITLE
form.model is wrong when use a nested array of groups

### ISSUE THREAD

**Issue by MiniSuperDev** [artflutter/reactive_forms_generator#110]
![image](https://github.com/artflutter/reactive_forms_generator/assets/105388540/cfc86d6a-448a-4873-97ab-2d72fa747419)

The error is when you add an item to a subGroupList, the item is added to the form, but it is not reflected when calling `form.model`

Thank you

```dart
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:reactive_forms_annotations/reactive_forms_annotations.dart';

part 'main.freezed.dart';
part 'main.g.dart';
part 'main.gform.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  String modelString = '';
  String formValueString = '';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SingleChildScrollView(
          child: Column(
            children: [
              Form1FormBuilder(
                builder: (context, formModel, child) {
                  return Column(
                    children: [
                      ElevatedButton(
                        onPressed: () {
                          setState(() {
                            formModel.addGroupListItem(Group(
                              id: 'id_1',
                              subGroupList: [],
                            ));
                            formModel.groupListGroupForm
                                .elementAt(0)
                                .addSubGroupListItem(
                                  SubGroup(
                                    id: 'sub_id_1',
                                  ),
                                );

                            modelString = JsonEncoder.withIndent('  ').convert(
                              formModel.model.toJson(),
                            );
                            formValueString = JsonEncoder.withIndent('  ')
                                .convert(formModel.form.value);
                          });
                        },
                        child: Text(
                            'Add item to nested array of groups (subGroupList)'),
                      ),
                      Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Expanded(
                            child: Column(
                              children: [
                                SelectableText('Form value'),
                                SelectableText(formValueString),
                              ],
                            ),
                          ),
                          Expanded(
                            child: Column(
                              children: [
                                SelectableText('Model'),
                                SelectableText(modelString),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ],
                  );
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

@ReactiveFormAnnotation()
@FormGroupAnnotation()
@freezed
class SubGroup with _$SubGroup {
  const factory SubGroup({
    @FormControlAnnotation() required String id,
  }) = _SubGroup;

  factory SubGroup.fromJson(Map<String, dynamic> json) =>
      _$SubGroupFromJson(json);
}

@ReactiveFormAnnotation()
@FormGroupAnnotation()
@freezed
class Group with _$Group {
  const factory Group({
    @FormControlAnnotation() required String id,
    @FormArrayAnnotation<dynamic>() required List<SubGroup> subGroupList,
  }) = _Group;

  factory Group.fromJson(Map<String, dynamic> json) => _$GroupFromJson(json);
}

@ReactiveFormAnnotation()
@FormGroupAnnotation()
@freezed
class Form1 with _$Form1 {
  const factory Form1({
    @FormArrayAnnotation<dynamic>() required List<Group> groupList,
  }) = _Form1;

  factory Form1.fromJson(Map<String, dynamic> json) => _$Form1FromJson(json);
}



```

```yaml
name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  reactive_forms_annotations: ^1.1.0
  reactive_forms_generator: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

```
